# Generated by Django 5.0.6 on 2024-07-05 08:29

import account.validator
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('SAV', 'SAVINGS'), ('CUR', 'CURRENT'), ('DOM', 'DOMICILIARY')], default='SAV', max_length=3),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.CharField(default='0000', max_length=4, validators=[account.validator.validate_pin]),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('P', 'PENDING'), ('S', 'SUCCESSFUL'), ('F', 'FAILED')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEB', 'DEBIT'), ('CRE', 'CREDIT'), ('TRAN_OUT', 'TRANSFER_OUT'), ('TRAN_IN', 'TRANSFER_IN')], default='CRE', max_length=8),
        ),
    ]
